<!--
/******************************************************************
*** Po jistych problemech asi dropuju vyhledavani dle keywords  ***
***  a pokracuji s vyhledavanim skrze LIKE, byt je pomalejsi... ***
******************************************************************/
-->    
<h1>Keywords</h1> 
<?php if ($names):?>
Write keywords into "keywords" table <a href="keywords/calculate/write">NOW</a>
<p>Names:  <?= count($names) ?><br>
<?php foreach ($names as $line){
    echo $line['name'] . "<br>";
} ?>
</p>
<p>Keywords: <?= count($keywords) ?> <br>
<?php foreach ($keywords as $line){
    echo $line . "<br>";
} ?>
</p>
<?php else: ?>
<a href="/keywords/calculate">Vypsat vsechny keywords</a><br>
<a href="/keywords/map/anime">Zapsat navaznosti keywords s obsahem pro ANIME</a><br>
<a href="/keywords/map/manga">Zapsat navaznosti keywords s obsahem pro MANGU</a><br>
<a href="/keywords/map/serial">Zapsat navaznosti keywords s obsahem pro SERIALY</a><br>
<?php endif; ?>