<?php 


/*------------------------------------
-------------FOR DELETION-------------
-------------------------------------- */



if ($data):
    $row = 1;
    $itemsPerRow = 3;
    $length = count($data); 
    if ($itemsPerRow < $length):
        $linkNext = " onClick='cycleCarousel(\"right\");' ";
        $linkPrewious = " onClick='cycleCarousel(\"left\");' ";?>
        <img src onError='cycle();'>
    <?php else : $inactive = " inactive"; endif; ?>
<div>
    <div class="wrapper">
        <div class="prewious<?= $inactive?>" <?= $linkPrewious?> >
        <i class="fas fa-angle-left"></i>
        </div>
        <div class="content">
            <div id="container" class="container"  name="show" >
                <?php for ($i=0; $i<$length; $i++) :
                        //print_r($data[$i]);
                        switch ($data[$i]['type']){
                            case "anime":
                                $ribbonType = "Anime";
                                break;
                            case "manga":
                                $ribbonType = "Manga";
                                break;
                            case "serial":
                                $ribbonType = "Seriál";
                        }
                        $hidden = '';
                        if (!$records[$i]['link']) { $hidden = ' hidden';}
                        if ($i >= ($itemsPerRow * $row)) { $row++; echo "</div>\n <div id='container' name='hide' class='container hidden'>";}
                        $progress = "e" . $records[$i]['episode'];
                        if ($records[$i]['series'] != 0) { $progress = "s" . $records[$i]['series'] . $progress;}
                        if (strlen($data[$i]['name']) > 22) { $name = substr($data[$i]['name'], 0, 22) . "...";} else {$name = $data[$i]['name'];}
                        ?>
                        <div class="indexItem itemDefault">
                            <span class="indexName" title='<?= $data[$i]['name'] ?>'><?= $name ?></span><br>
                            <div class="itemImage indexItemImage">
                                <div class="itemImageRibbon">
                                    <div class="ribbonText">
                                        <?= $ribbonType ?>
                                    </div>
                                </div>
                                <img src="<?= $data[$i]['image'] ?>">
                            </div>

                            <form style="display:none;" id="plusOne<?= $records[$i]['_id']?>" method="post" action="/muj-seznam">
                                <input type="hidden" id="plusOne" name="plusOne" value="true">
                                <input type="hidden" id="checked" name="checked" value="<?= $checked ?>">
                                <input type="hidden" id="origin" name="origin" value="uvod">
                                <input type="hidden" id="_id" name="_id" value="<?= $records[$i]['_id']  ?>">
                            </form>
                            <a class="plusButton indexLeft" onclick="document.forms['plusOne<?= $records[$i]['_id']?>'].submit();" title="Navýšit poslední díl/kapitolu o jeden..."><span>+1</span></a> <!-- +1 icon -->
                            <i class="infoButton indexCenter" title="<?= $progress ?>">i</i> <!-- info -->
                            <span class="playButton indexRight <?= $hidden?>" title="Přejít na sledování/čtení dalšího dílu/kapitoly."><a href="<?= $records[$i]['link']?>" target="_blank"><i class="fas fa-play"></i></a></span> <!-- play icon -->
                            
                        </div>
                <?php endfor; ?>
            </div>
        </div>
        <div class="next<?= $inactive?>" <?= $linkNext?> >
            <i class="fas fa-angle-right"></i>
        </div>
    </div>
</div>
    
<?php else: ?>
    <h3>Nemáte v seznamu žádné záznamy.</h3>
<?php endif;?>
