<div class="index-section kontakt-section">
    <div class="index-section-title">Seznam zabanovaných</div>

    <form method="post" id="ban">
        <br />
        Přidat BAN uživateli:<br />

        <div class="form__group field" title="Jméno uživatele:">
            <input type="text" required="required" class="form__field" placeholder="Jméno uživatele:" name="username" id='username' />
            <label for="name" class="form__label">Jméno uživatele:</label>
        </div>

        <div class="button accept" onclick="document.forms['ban'].submit();">ZaBANovat</div>
    </form> <br />

    <table class="reports">
        <tr>
            <th>ID</th>
            <th>Jméno</th>
            <th>Email</th>
            <th>Páva</th>
            <th>Úprava</th>
        </tr>

        <?php foreach ($bans as $ban):
            if ($ban['rights'] == -1) { $rights = 'Silence';} else { $rights = 'BAN';} ?>
            <tr>
                <td><?= $ban['_id'] ?></td>
                <td><?= $ban['username'] ?></td>
                <td><?= $ban['email'] ?></td>
                <td><?= $rights ?></td>
                <td>
                    <a href="ban/less/<?= $ban['_id'] ?>"><i class="fa fa-plus-circle" title="Snížit intenzitu BANu"></i></a>
                    <a href="ban/more/<?= $ban['_id'] ?>"><i class="fa fa-minus-circle" title="Zvýšit intenzitu BANu"></i></a>
                </td>
            </tr>
        <?php endforeach;?>
    </table>

</div>








