<div class="index-section cekarna">
    <div class="index-section-title">Seznam položek k autorizaci</div>

    <form id="authorize" method="post">
        <div class="button accept" onclick="document.forms['authorize'].submit();">Zveřejnit vybrané</div><br />
        
        <input id="getAll" type="checkbox" onchange='handleChange(this);'>
        <label for="getAll">Vybrat vše</label>

        <div class="cekarna-container">
            <?php 
            $cekarna = true;

            $data = $serials;
            $type = 'serial';
            include "views/items.phtml"; 

            $data = $animes;
            $type = 'anime';
            include "views/items.phtml"; 

            $data = $mangas;
            $type = 'manga';
            include "views/items.phtml"; ?>
        </div>
        
    </form>

</div>
