<div class="index-section gdpr">
    <div class="index-section-title">Cookies:</div>

    <h1>Co jsou soubory cookies?</h1>
    Cookies jsou malé textové informace, které se ukládají ve vašem prohlížeči. Ukládají se ve vašem internetovém prohlížeči a lze se na ně podívat, 
    lze je vypnout (zakázat ukládání) nebo smazat.<br>

    <h1>Jaké jsou typy souborů cookies?</h1>
    esenciální - slouží pro základní funkcionalitu webu<br>
    analytické - slouží pro měření návštěvnosti a různých statistik webu<br>
    remarketingové/inzertní - slouží k lepšímu cílení a personalizaci reklam, které uvidíte jinde na webu<br>

    <h1>Které soubory cookies využíváme?</h1>
    <p>Cookies tohoto serveru - gewrit.4fan.cz - jen pro provozní účely a personalizované nastavení webu.</p> 
    Dále tato webová stránka používá cookies třetích stran, které jsou ukládané na jiné doméně.<br>

    <h2>Jde o tyto služby:</h2>

    <p>Google Analytics, služba webové analytiky poskytované společností Google Inc. ("Google"). 
        Informace poskytnuté souborem cookie o užívání této webové stránky jsou obvykle přeneseny na server společnosti Google v USA a tam jsou uloženy. 
        Více na <a href="https://www.google.com/intl/cs/policies/technologies/cookies/" target="_blank">https://www.google.com/intl/cs/policies/technologies/cookies/</a></p>
    
    <p>Používáním tohoto webu s tímto zpracováním cookies souhlasíte.</p> 
    
</div>
