<div class="kontaktContainer">
    <h1>Detail</h1>
    <form method="post">
    ID: <?= $data['_id'] ?>, Typ: <?= $type ?><br /><br />
    <input type="hidden" name="_id"  value="<?= $data['_id'] ?>"/>
    <?= $data['name'] ?><br />
    <img src="<?= $data['image'] ?>"><br />
    Rok<br />
    <?= $data['year'] ?><br />
    Žánr<br />
    <?= $data['genre'] ?>"<br />
    <?php if ($type == 'serial') : ?>
        <a href="<?= $data['linkCsfd'] ?>" title="odkaz na CSFD" target="_blank"><li class="csfd">CSFD</li> </a> 
        <a href="<?= $data['linkImdb'] ?>" title="odkaz na IMDB" target="_blank"><li class="imdb">IMDB</li> </a><br>
    <?php endif; ?>
    <?php if ($type != 'serial') : ?>
        <a href="<?= $data['linkAp'] ?>" title="odkaz na Anime-planet" target="_blank"><li class="ap">Anime-planet</li> </a><br />
    <?php endif; ?>
    Popis<br />
    <?= $data['description'] ?><br />
    Na seznamu <?= $inListCount ?>x<br>
    Hodnocení: <?= $data['rating'] ?> * (hodnoceno <?= $data['ratingQuantity'] ?>x)<br>
    <?php if ($userRating):?>
        Vaše hodnocení : <?= $userRating ?> *
    <?php endif;?>
</form>

</div>