<div class="index-section detail-section">
    <?php 
    if ($inListCount == 0){
        $thisItemEnd = "ještě nemá nikdo na seznamu.";
    } elseif ($inListCount == 1){
        $thisItemEnd = "má na seznamu " .  $inListCount  . " uživatel.";
    } elseif ($inListCount >= 2) {
        $thisItemEnd = "mají na seznamu " .  $inListCount  . " uživatelé.";
    } elseif (($inListCount >= 5) || ($inListCount == 0)) {
        $thisItemEnd = "má na seznamu " .  $inListCount  . " uživatelů.";
    }
    switch ($type){
        case 'serial':
            $titleText = "Detail seriálu";
            $thisItem = "Tento seriál " . $thisItemEnd;
            break;
        case 'anime':
            $titleText = "Detail anime";
            $thisItem = "Toto anime " . $thisItemEnd;
            break;
        case 'manga':
            $titleText = "Detail mangy";
            $thisItem = "Tuto mangu " . $thisItemEnd;
            break;
    }

    if ($data['ratingQuantity'] == 0){
        $rating = "N/A";
        $ratingQuantity = "Zatím nehodnoceno.";
    } else {
        if ($data['ratingQuantity'] == 1) {
            $ratingQuantity = "Hodnotil " . $data['ratingQuantity'] . " uživatel.";
        } elseif (($data['ratingQuantity'] >= 2) && ($data['ratingQuantity'] < 5))  {
            $ratingQuantity = "Hodnotili " . $data['ratingQuantity'] . " uživatelé.";
        } elseif ($data['ratingQuantity'] >= 5) {
            $ratingQuantity = "Hodnotilo " . $data['ratingQuantity'] . " uživatelů.";
        }
        $rating = $data['rating'] . " / 5";
        
    }

    ?>
    <div class="index-section-title">
        <?= $titleText ?>
    </div>

    <div>
        <img src="<?= $data['image'] ?>">
        
        <?php if (is_integer($userRights)):?>
            <div class="detail-tools">
                <?php if ($userRights >= 0):?>
                    <a href="pridat-do-seznamu/<?= $type ?>/<?= $data['_id'] ?>"><i class="fas fa-plus"></i>Přidat</a> <br>
                    <a href="nahlasit/<?= $type ?>/<?= $data['_id'] ?>"><i class="fas fa-bug"></i>Nahlásit</a> <br>
                <?php endif; 
                if ($userRights >= 1):?>
                    <a href="editor/<?= $type ?>/<?= $data['_id'] ?>"><i class="fas fa-edit"></i>Upravit</a>
                <?php endif; ?>
            </div>
        <?php endif;?>
        
    </div>

    <div class="detail-text">
        <div class="detail-name"> 
            <?= $data['name'] ?> 
        </div>

        <div class="detail-row"> 
            <div><?= $data['year'] ?></div>
            <div class="show-rating">
                <i class="fas fa-star active-star"></i> Hodnocení: <?= $rating ?>
                <div class="detail-rating">
                    <?= $ratingQuantity ?><br>
                    <?php if ($userRights >= 0) {?>
                        

                        <form id="rate" method="post" onchange="document.forms['rate'].submit();">
                            <?php if ($userRating) {?>
                                Vaše hodnocení - <?= $userRating ?> <i class="fas fa-star"></i> <br>
                                <input type="radio" id="0" name="userRating" value="0">
                                <label for="0">Odebrat hodnocení</label><br>
                            <?php } ?>
                            <input type="radio" id="1" name="userRating" value="1">
                            <label for="1"><i title="Hodnotit 1*" class="fas fa-star<?php if ($userRating >= 1){ echo ' active-star'; } ?> star-big"></i></label>
                            <input type="radio" id="2" name="userRating" value="2">
                            <label for="2"><i title="Hodnotit 2*" class="fas fa-star<?php if ($userRating >= 2){ echo ' active-star'; } ?> star-big"></i></label>
                            <input type="radio" id="3" name="userRating" value="3">
                            <label for="3"><i title="Hodnotit 3*" class="fas fa-star<?php if ($userRating >= 3){ echo ' active-star'; } ?> star-big"></i></label>
                            <input type="radio" id="4" name="userRating" value="4">
                            <label for="4"><i title="Hodnotit 4*" class="fas fa-star<?php if ($userRating >= 4){ echo ' active-star'; } ?> star-big"></i></label>
                            <input type="radio" id="5" name="userRating" value="5">
                            <label for="5"><i title="Hodnotit 5*" class="fas fa-star<?php if ($userRating == 5){ echo ' active-star'; } ?> star-big"></i></label>
                        </form>

                    <?php } else { echo "Nelze hlasovat."; } ?>

                </div>
            </div>
        </div>

        <div>
            <u>Žánr:</u> <?= $data['genre'] ?>
        </div>

        <div>
            <u>Popis:</u> <?= $data['description'] ?>
        </div>

        <div class="detail-links">
            <?php if ($type == 'serial') : ?>
                <a href="<?= $data['linkCsfd'] ?>" title="odkaz na CSFD" target="_blank"><div class="button csfd">CSFD</div> </a> 
                <?php if ($data['linkImdb'] != '') { ?>
                    <a href="<?= $data['linkImdb'] ?>" title="odkaz na IMDB" target="_blank"><div class="button imdb">IMDB</div> </a>
                <?php }; ?>
            <?php endif; ?>
            <?php if ($type != 'serial') : ?>
                <a href="<?= $data['linkAp'] ?>" title="odkaz na Anime-planet" target="_blank"><div class="button ap">Anime-planet</div> </a>
            <?php endif; ?>
        </div>

        <div>
            <?= $thisItem ?>
        </div>

        
        
    </div>

</div>