<div>
    <ul>
        <li><a href="/faq">Otázky & odpovědi</a></li>
        <li><a href="/podminky-uziti">Podmínky užití</a></li>
        <li><a href="/statistiky">Statistiky</a></li>
    </ul>
</div>

<div>
    <ul>
        <li><a href="#">O nás</a></li>
        <li><a href="/kontakt">Kontakt</a></li>
    </ul>
</div>

<div>
    Můžete nás sledovat na facebooku<br>
    <a class="footer-facebook" href="#" target="_blank"><i class="fab fa-facebook footer-facebook"></i></a>
</div>

<div>
    © Gewrit 2020<br>
    Code & design by <a href="http://ghasteek.4fan.cz/" target="_blank">Ghasteek</a>
</div>