<div class="index-section gdpr">
    <div class="index-section-title">Souhlas se zpracováním osobních údajů:</div>

    <p>
        Základní pojmy:<br />

        Provozovatel = Tomáš Podolský (podolsky.tomas@gmail.com)<br />
        Portál = <a href="http://gewrit.4fan.cz" target="_blank">gewrit.4fan.cz</a>
    </p> 

    <p>
        Tímto uděluji souhlas Provozovateli Portálu, se zpracováním osobních údajů dle podmínek uvedených níže a dále také v <a href="/podminky-uziti" target="_blank">Podmínách užití</a> .<br />
        Osobní údaje jsou zpracovávány v rozsahu, ve kterém byly poskytnuté Provozovateli (vytvořením profilu - formulářem na Portále a získané během mého užívání Portálu. 
        V případě, že se budu účastnit soutěží a jiných podobných akcí, které bude rovněž pořádat Provozovatel, zároveň tímto souhlasím se zpracováním případných dodatečných údajů, 
        vyplněných formulářem v rámci této dané akce či soutěže. I po jejím ukončení. Na mysli je tak jméno, příjmení a adresa + technické údaje jako IP adresa a cookies 
        (dále jen „Osobní údaje“). Právním základem pro zpracování Osobních údajů je tento souhlas, kterým je Provozovatel oprávněn zpracovávat Osobní údaje za účelem zajištění 
        realizace marketingu, průzkumů a obchodních statistik skrze zasílání obchodních sdělení ve smyslu zákona č. 480/2004 Sb., o některých službách informační společnosti 
        (i zasílání obchodních sdělení elektronickými prostředky), pozvánek na akce pořádané Provozovatelem, poskytování odborných a marketingových informací, to vše jakýmikoliv 
        prostředky komunikace, zejména e-mailem a prostřednictvím Portálu.<br />
        Dále tímto Provozovateli uděluji souhlas s tím, že na základě Osobních údajů může provádět profilování a jejich zpracovávání za pomoci automatizovaných programů, 
        aby uživatelům byly poskytovány nabídky a výhody, které budou odpovídat právě jejich zájmům. Díky tomu se mohou pro jednotlivé uživatele poskytované nabídky a 
        výhody lišit a přicházet pouze některým z nich.
    </p> 

    <p>
        Beru na vědomí, že k Osobním údajům budou mít kromě Provozovatele přístup ještě třetí osoby, v rámci Evropské unie – zpracovatelé, kteří poskytují vhodné záruky a jejichž 
        zpracování splňuje požadavky dle platných právních předpisů, a které zajišťuje náležitou ochranu vašich práv. Tento souhlas uděluji na dobu trvání mého členství zde na Portále, 
        nebo do jeho odvolání, což mohu učinit kdykoliv a ukončit tak zároveň mé členství. Odvoláním souhlasu není dotčena zákonnost zpracování vycházejícího ze souhlasu, 
        který byl dán před jeho odvoláním. Odvolání souhlasu též nemá vliv na zpracování Osobních údajů, jenž zpracovává Provozovatel dle jiného právního základu, než je souhlas 
        (zejména je‐li to nutné pro splnění smlouvy, právní povinnosti, případně i z dalších důvodů, uvedených v platných právních předpisech.) Spolu s udělením souhlasu potvrzuji,
        že jsem seznámen(a) s Podmínkami užití a se všemi právy, které mi v souvislosti se zpracováním osobních údajů Provozovatelem náleží.
    </p>
    
</div>
