<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/gewrit" />
        <meta charset="UTF-8" />
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keywords ?>" />
        <link rel="stylesheet" href="style.css" type="text/css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://kit.fontawesome.com/1648622916.js" crossorigin="anonymous"></script>
    </head>
    <style></style>
    <body onLoad="getHeight(); removeFadeOut('message', 3000, 5000);">
        <div id="message" class='message'>
            <?php
                $no = 0; 
                foreach ($messages as $message) : 
                $no += 1; ?>
                <p name="message" id="message<?= $no ?>" class="<?= $message[1] ?>" onClick="closeMessage('message<?= $no ?>')"> <i class="fas fa-info-circle"></i> <?= $message[0] ?> <i class='fa fa-close'></i> </p>
            <?php endforeach ?>
        </div>

        <header>
            <div class="menu-container">
                <h1 class="logo">GEWRIT</h1>

                <nav class="site-nav" id="nav">
                    <ul class="menu-main">
                        <li><a <?php if ($title == 'Gewrit') { echo "class='active'"; }?> href="uvod"><i class="fas fa-home"></i></a></li>
                        <li><a <?php if ($title == 'Gewrit - Seriály') { echo "class='active'"; }?> href="serialy">Seriály</a></li>
                        <li><a <?php if ($title == 'Gewrit - Anime') { echo "class='active'"; }?> href="anime">Anime</a></li>
                        <li><a <?php if ($title == 'Gewrit - Manga') { echo "class='active'"; }?> href="manga">Manga</a></li>
                        <?php UserAdministration::showMyList($title); ?>
                    </ul>
                    <ul class="menu-profile">
                        <?php UserAdministration::showProfile(); ?>
                    </ul>
                </nav>
                <div onClick="toogleMenu()" class="menu-toggle" id="menu-toggle">
                    <div class="hamburger"></div>
                </div>
            </div>
        </header>


        <article>
            <?php $this->controller->showView(); ?>
        </article>

        <footer>
            <p>Patička</p>
        </footer>

        <script src="index.js"></script>
    </body>
</html>