<div class="index-section index">
    <div class="index-section-title">
        <h1>Vítejte na Gewritu</h1>
    </div>

    <p>Gewrit je portál, kde si můžete vést záznamy Vámi sledovaných seriálů, anime a čtené mangy. Jednoduše si vyhledejte Váš oblíbený seriál, anime či mangu v naší databázi a 
        přidejte si jej/ji do svého seznamu. Pokud nenajdete co jste hledali, můžete nám pomoci s rozšiřováním databáze a poslat nám odkaz (více <a href="/faq">zde</a> ).
    </p> 

    <div class="index-summary-container">

        <span>Najdete u nás</span> 
        <div class="index-summary-container-row">
            <div class="index-summary-column">
                <i class="fas fa-users"></i>
                <?= $allUserCount ?> uživatelů
            </div>
            <div class="index-summary-column">
                <i class="fas fa-sticky-note"></i>
                <?= $allItemsCount?> položek v databázi
            </div>
        </div>

        <a href="/registrace" title="Přejít na stranu s registrací."><div class="button accept">Vytvořit profil</div></a>
    </div>

    <p>
        Po registraci si můžete do svého seznamu přidávat seriály/anime/mangu. Ve svém seznamu máte podkategorie jako sledované, odložené, pozastavené, do kterých si můžete své 
        záznamy rozdělit a pak si je podle těchto kategorií i roztřídit. Ke každému Vašemu záznamu si také můžete uložit odkaz odkud sledujete/čtete, abyste měli možnost rychlého skoku
        na další díl/kapitolu. Jakožto registrovaný uživatel můžete i hodnotit <i class="far fa-smile"></i>.
    </p>

    <p>Tak šup šup, <a href="/uvod">pokračujte na úvodní stranu</a> a trošku se porozhlédněte <i class="far fa-smile-wink"></i>. Budeme rádi, 
    když se zaregistrujete a případně o nás řeknete Vašim známým. </p>

    <p>Pokud máte jakékoliv otázky, zkuste se podívat na <a href="/faq">otázky a odpovědi</a>, pokud tam odpověď nenajdete, můžete nás <a href="/kontakt">kontaktovat</a> a my 
        se vynasnažíme Vám co nejdříve odpovědět.
    </p>

</div>
