<?php 
if ($data):
    switch ($type){
        case "anime":
            $ribbonType = "Anime";
            break;
        case "manga":
            $ribbonType = "Manga";
            break;
        case "serial":
            $ribbonType = "Seriál";
    }
foreach ($data as $line): 
    $style = '';
    $br = '';
    if (strlen($line['genre']) > 17) { $genre = substr($line['genre'],0,17) . " ...";} else { $genre = $line['genre']; }; 
    if ($line['onlyFor'] != 0) { $style = $style . ' forApproval'; }; ?>
    <div class="unitBox itemDefault<?= $style ?>">
        <div class="itemImage">
            <div class="itemImageRibbon">
                <div class="ribbonText">
                    <?= $ribbonType ?>
                </div>
            </div>
            <a href="/detail/<?= $type?>/<?= $line['_id']?>"><img src="<?= $line['image'] ?>" title="hodnoceni - <?= $line['rating']?> | <?= $line['ratingSum']?>/<?= $line['ratingQuantity']?>"></a>
        </div>
        <div class="unitBoxText">
            <strong> <?= $line['name'] ?> </strong> <i class="fa fa-info-circle" title="<?= $line['description'] ?>"></i><br>
            <div>
                <?= $line['year'] ?><br>
                <span title="<?= $line['genre'] ?>">Žánr: <?=  $genre ?></span>
            </div> 
            <?php if ($type == 'serial'):?>
                <a href="<?= $line['linkCsfd'] ?>" title="odkaz na CSFD" target="_blank"><li class="csfd">CSFD</li> </a> 
                <a href="<?= $line['linkImdb'] ?>" title="odkaz na IMDB" target="_blank"><li class="imdb">IMDB</li> </a>
            <?php endif;
                if (($type == 'anime') || ($type == 'manga')) :?>
                    <a href="<?= $line['linkAp'] ?>" title="odkaz na Anime-planet" target="_blank"><li class="ap">Anime-planet</li> </a>
                <?php endif; //echo $userRights;
            if ($userRights >= -1): ?>
                <br><br>
                <a href="/nahlasit/<?= $type ?>/<?= $line['_id']?>"><i class="fa fa-wrench" title="Nezobrazuje se obrázek, název, nebo je cokoliv v nepořádku? Kliknutím na tuto ikonku nám to nahlásíte a my to vyřešíme :-) "> Nahlásit</i></a>
                <a href="/pridat-do-seznamu/<?= $type ?>/<?= $line['_id']?>"><i class="fa fa-plus-circle" title="Přidat do seznamu sledovaných."> Přidat</i></a>
                <?php if ($userRights > 0): ?>
                    <a href="/editor/<?= $type ?>/<?= $line['_id'] ?>"><i class="fa fa-edit" title="Upravit anime."></i>Upravit</a>
                    <br>
                    <?php if (($line['onlyFor'] != 0) && $cekarna): ?>
                        ID autora: <?= $line['onlyFor']?> | <a href="/profil/<?= $line['onlyFor']?>">Profil</a> | <a href="/nahlasit/uzivatel/<?= $line['onlyFor']?>">Nahlásit</a><br>
                        <input class="checkAll" type="checkbox" name="<?= $type ?>[]" value="<?= $line['_id'] ?>"/> Autorizovat
                    <?php endif; ?>
                <?php endif;
            endif; ?>
        </div>
    </div>
    <?= $br ?>
<?php 

endforeach;
else: ?>
<h3>Bohužel, v databázi jsme nenašli žádné záznamy</h3>
<?php endif;?>