<?php foreach ($data as $i=>$line):

    if ($seznamType == 'all'){
        $seznamStyle = " list-item";
    } else {
        $seznamStyle = "";
    }

    if ($line['onlyFor'] != 0){
        $exclamationMark = " <i title='Není veřejné, čeká na schválení.' class='fas fa-exclamation-triangle'></i>";
    } else {
        $exclamationMark = "";
    }

    
    switch ($line['type']){
        case "anime":
            $itemType = "Anime";
            $type = "anime";
            break;
        case "manga":
            $itemType = "Manga";
            $type = "manga";
            break;
        case "serial":
            $itemType = "Seriál";
            $type = "serial";
    }

    $progress = "e" . $records[$i]['episode'];
    if ($records[$i]['series'] != 0) { $progress = "s" . $records[$i]['series'] . " " . $progress;}

    if ($records[$i]['link'] == '') { $hidden = 'class="hidden"'; $reverse = " reverse"; } else { $hidden = ""; $reverse = ""; }

    if (strlen($line['name']) > 22) { $name = substr($line['name'], 0, 22) . "...";} else {$name = $line['name'];}
    if ($seznamType == 'all'){echo "<div class='list-item'>\n" ;}?>

<div class="index-item">

    <div class="index-item-mask-container">

        <?php if ($line['rating'] != 0):?>
            <div class="index-item-star">
                <i class="fas fa-star"></i>
                <span class="index-item-rating"><?= $line['rating'] ?></span>
            </div>
        <?php endif; ?>

        <img class="index-item-image" src="<?= $line['image'] ?>">

        <div class="index-item-mask">
            <a class="index-item-detail" href="/detail/<?= $type ?>/<?= $line['_id'] ?> " title="Otevře detail položky."><i class="fas fa-search"></i> DETAIL</a>
            <?php if ($line['rating'] != 0):?>
                <div class="item-rating-tooltip" title="Průměr <?= $line['rating'] ?> (z <?= $line['ratingQuantity'] ?> hlasů). Hlasovat můžete na detailu.">
                    Hodnocení: <?= $line['rating'] ?> <i class="fas fa-star"></i>
                </div>
                
            <?php endif;?>

            <div class="item-rating-tooltip" title="<?= $line['description'] ?>">
                <i class="fas fa-info"></i> Popis
            </div>

            <?php if ($userRights >= -1){
                if ($today){ ?>
                    <div><?= $itemType?></div>
                    <div><?= $progress?></div>
                    <div class="item-tools-bar<?= $reverse?>">
                         
                         <!-- play icon -->
                        <a <?= $hidden?> title="Přejít na sledování/čtení dalšího dílu/kapitoly." href="<?= $records[$i]['link']?>" target="_blank"><i class="fas fa-play"></i></a>

                        <!-- hidden form for +1 funcionality -->
                        <form style="display:none;" id="plusOne<?= $records[$i]['_id']?>" method="post" action="/muj-seznam">
                            <input type="hidden" id="plusOne" name="plusOne" value="true">
                            <input type="hidden" id="origin" name="origin" value="uvod">
                            <input type="hidden" id="_id" name="_id" value="<?= $records[$i]['_id']  ?>">
                        </form>

                        <!-- +1 icon -->
                        <a onclick="document.forms['plusOne<?= $records[$i]['_id']?>'].submit();" title="Navýšit poslední díl/kapitolu o jeden...">+1</a> 
                    </div>
                <?php } else { ?>
                    <a href="/pridat-do-seznamu/<?= $type ?>/<?= $line['_id'] ?>" title="Přidá položku do vašeho seznamu"><i class="fas fa-plus"></i> PŘIDAT</a>
                <?php }
            }?>
        </div>

    </div>

    <div class="index-name" title='<?= $line['name'] ?>'><?= $name . $exclamationMark ?></div>

</div>
<?php 
if ($seznamType == 'all'){echo "</div>\n";}
endforeach;?>