<div class="index-section kontakt-section">
    <div class="index-section-title">Kontaktujte nás</div>

    <p>
        Kontaktovat nás můžete více možnostmi. Můžete napsat email na gewrit.4fan@gmail.com , vynasnažíme se Vám co nejdříve odpovědět.
    </p>

    <p>
        Případně nám můžete poslat zprávu na naší <a href="https://facebook.com/" target="_blank">facebookové stránce</a>. 
    </p>

    <p>
        A nebo použijte kontaktní formulář níže <i class="far fa-smile"></i>.
    </p>

    <form method="post" id="form-email">

        <div class="form__group field" title="Vaše emailová adresa. Ta bude použita jen v případě obnovení zapomenutého hesla.">
            <input type="text" required="required" class="form__field" placeholder="Email" name="email" id='email' value="<?php if (isset($_POST['email'])) { echo(htmlspecialchars($_POST['email']));} else { echo($email);} ?>"/>
            <label for="email" class="form__label">Email:</label>
        </div>

        <div class="form__group field" title="Zadejte aktuální rok, je to ochrana proti spamu.">
            <input type="text" required="required" class="form__field" placeholder="Aktuální rok (antispam):" name="year" id='year' />
            <label for="year" class="form__label">Aktuální rok:</label>
        </div>

        <div class="kontakt-textarea">
            <label for="text">Vaše zpráva:</label><br />
            <textarea name="text" placeholder="Zde nám napište, co máte na srdci..."><?php if (isset($_POST['text'])) echo(htmlspecialchars($_POST['text'])); ?></textarea>
        </div>

        <div> <i>Odesláním formuláře souhlasíte se <a href="/gdpr" target="_blank">zpracováním osobních údajů</a></i> </div>
        

        <div class="button accept" onclick="document.forms['form-email'].submit();" >Odeslat</div>
    </form>
    
</div>


