<?php foreach ($latestData as $line):

    if (strlen($line['name']) > 22) { $name = substr($line['name'], 0, 22) . "...";} else {$name = $line['name'];}?>

<div class="index-item">
    <img class="index-item-image" src="<?= $line['image'] ?>">
    <div class="index-name" title='<?= $line['name'] ?>'><?= $name ?></div>

    <div class="index-item-mask">
        <a href="/detail/<?= $type ?>/<?= $line['_id'] ?>" title="Detail">+ DETAIL</a>
    </div>

    <?php if (!$isLogged):?>
    <a class="plusButton indexLeft" href="/pridat-do-seznamu/<?= $type ?>/<?= $line['_id'] ?>" title="Přidat do seznamu"><span class="justPlus">+</span></a> <!-- + icon -->
    <?php endif;?>
</div>

<?php endforeach;?>