<?php foreach ($latestData as $line):

    if (strlen($line['name']) > 22) { $name = substr($line['name'], 0, 22) . "...";} else {$name = $line['name'];}?>

<div class="index-item">

    <div class="index-item-mask-container">
        <img class="index-item-image" src="<?= $line['image'] ?>">
        <div class="index-item-mask">
            <a class="index-item-detail" href="/detail/<?= $type ?>/<?= $line['_id'] ?> " title="Detail"><i class="fas fa-search"></i> DETAIL</a><br>
            <?php if ($isLogged):?>
                <a class="index-item-add" href="/pridat-do-seznamu/<?= $type ?>/<?= $line['_id'] ?>" title="Přidá položku do vašeho seznamu"><i class="fas fa-plus"></i> PŘIDAT</a>
            <?php endif;?>
        </div>
    </div>
    <div class="index-name" title='<?= $line['name'] ?>'><?= $name ?></div>
</div>
<?php endforeach;?>