<div class="index-section kontakt-section">
    <div class="index-section-title">Seznam moderátorů</div>

    <form method="post" id="mod">
        <br />
        Přidat práva moderátora uživateli:<br />

        <div class="form__group field" title="Jméno uživatele:">
            <input type="text" required="required" class="form__field" placeholder="Jméno uživatele:" name="username" id='username' />
            <label for="username" class="form__label">Jméno uživatele:</label>
        </div>

        <div class="button accept" onclick="document.forms['mod'].submit();">Povýšit</div>
    </form>

    <table class="reports">
        <tr>
            <th>ID</th>
            <th>Jméno</th>
            <th>Email</th>
            <th>Páva</th>
            <th>Úprava</th>
        </tr>

        <?php foreach ($mods as $mod):
            if ($mod['rights'] == 1) { $rights = 'Mod';} else { $rights = 'Admin';} ?>
            <tr>
                <td><?= $mod['_id'] ?></td>
                <td><?= $mod['username'] ?></td>
                <td><?= $mod['email'] ?></td>
                <td><?= $rights ?></td>
                <td>
                    <a href="mod/promote/<?= $mod['_id'] ?>"><i class="fa fa-plus-circle" title="Zvýšit práva"></i></a>
                    <a href="mod/degrade/<?= $mod['_id'] ?>"><i class="fa fa-minus-circle" title="Snížit práva"></i></a>
                </td>
            </tr>
        <?php endforeach;?>
    </table>

</div>
