<?php
if ($data): 
    foreach($data as $i => $line):
    
        switch ($line['type']) {
            case 'anime':
                $prefix = '<span class="prefix" title="Anime">A - </span>';
                $typeText = 'Anime';
                break;
            case 'manga':
                $prefix = '<span class="prefix" title="Manga">M - </span>';
                $typeText = 'Manga';
                break;
            case 'serial':
                $prefix = '<span class="prefix" title="Seriál">S - </span>';
                $typeText = 'Seriál';
                break;
        }

        if (!$records[$i]['link']) {
            $hiddenPlay = " class='hidden' ";
        } else {
            $hiddenPlay = "";
        }

        $lastRead = strtotime($records[$i]['timestamp']);
        $now = time();
        $days = round(($now - $lastRead)  / (60 * 60 * 24)) ;

        if (!$line["name"]) {
            $name = "Je nám líto, ale původní položka byla smazána z databáze. Poznamenejte si postup a zkuste si ji přidat znovu.";
        } else {
            $name = $line["name"];
        }

    
    ?>
    <div class="my-list-item">
        <div id ="div<?= $records[$i]['_id'] ?>" class="my-list-item-default" onClick="toogleFilter('div<?= $records[$i]['_id']?>', 'my-list-item-default-active');toogleFilter('details<?= $records[$i]['_id']?>', 'my-list-item-details-show');">
            <img src="<?= $line['image'] ?>" alt="404">

            <div class="my-list-item-middle-container">
                <div class="my-list-item-name"><?= $name?></div>

                <?= $typeText ?> - 
                    <?php if ($records[$i]['series'] != 0){ echo "s " . $records[$i]['series'] . " |";} ?>
                    <?php if (($line['type'] == 'serial') || ($line['type'] == 'anime')) echo "e "; else echo "ch " ?><?= $records[$i]['episode'] ?> <br>

                Poslední změna <?= date('j.m.Y', strtotime($records[$i]['timestamp']))?>  (<?= $days ?> dní)
            </div>

            <div class="my-list-item-tools-container">
                <!-- play icon -->
                <a <?= $hiddenPlay?> title="Přejít na sledování/čtení dalšího dílu/kapitoly." href="<?= $records[$i]['link']?>" target="_blank"><i class="fas fa-play"></i></a>

                <!-- hidden form for +1 funcionality -->
                <form style="display:none;" id="plusOne<?= $records[$i]['_id']?>" method="post" action="/muj-seznam">
                    <input type="hidden" id="plusOne" name="plusOne" value="true">
                    <input type="hidden" id="_id" name="_id" value="<?= $records[$i]['_id']  ?>">
                </form>

                <!-- +1 icon -->
                <a onclick="document.forms['plusOne<?= $records[$i]['_id']?>'].submit();" title="Navýšit poslední díl/kapitolu o jeden...">+1</a> 
            </div>
        </div>

        <div id="details<?= $records[$i]['_id']?>" class="my-list-item-details">
            <br>
            <?php include "views/progressForm.phtml"?>
        </div>

    </div>
    
    <?php
    endforeach;
endif;
?>