<div class="menu-container">
    <a href="/"><h1 class="logo">GEWRIT</h1></a>

    <nav class="site-nav" id="nav">
        <ul class="menu-main">
            <li><a <?php if ($title == 'Gewrit') { echo "class='active'"; }?> href="uvod"><i class="fas fa-home"></i></a></li>
            <li><a <?php if (($title == 'Gewrit - Seriály') || ($title == 'Gewrit - Detail seriálu')) { echo "class='active'"; }?> href="serialy">Seriály</a></li>
            <li><a <?php if (($title == 'Gewrit - Anime') || ($title == 'Gewrit - Detail anime')) { echo "class='active'"; }?> href="anime">Anime</a></li>
            <li><a <?php if (($title == 'Gewrit - Manga') || ($title == 'Gewrit - Detail mangy')) { echo "class='active'"; }?> href="manga">Manga</a></li>
            <?php UserAdministration::showMyList($title); ?>
        </ul>
        <ul class="menu-profile">
            <?php UserAdministration::showProfile(); ?>
        </ul>
    </nav>
    <div onClick="toogleMenu()" class="menu-toggle" id="menu-toggle">
        <div class="hamburger"></div>
    </div>
</div>