<div class="index-section">
    <div class="index-section-title">Obnova hesla</div>

    <?php if (!$tokenPassed):?>
    <form method="post" id="restore" class="restore-form"> 

        <div class="form__group field" title="Váš registrační email:">
            <input type="text" class="form__field" placeholder="Váš registrační email:" name="email" id='email'/>
            <label for="email" class="form__label">Váš registrační email:</label>
        </div>

        <div id="submit" class="button accept" onclick="document.forms['restore'].submit();" >Obnovit heslo</div>

    </form>
    <?php else:; ?>

    <form method="post" id="restore" class="restore-form"> 

        <div class="form__group field" title="Vaše heslo. Musí mít alespoň 5 znaků, z toho alespoň jedno velké písmeno a jedno číslo.">
            <input type="password" class="form__field" placeholder="Nové heslo:" name="newPassword" id='pwd' onkeyup="validatePassword(this.value);"/>
            <label for="newPassword" class="form__label">Nové heslo:</label>
            <span style="minHeight: 9em;" id="msg"></span>
        </div>

        <div class="form__group field" title="Prosím zopakujte Vaše heslo.">
            <input type="password" class="form__field" placeholder="Nové heslo znovu:" name="reNewPassword" id='rePwd' onkeyup="comparePassword(this.value);"/>
            <label for="reNewPassword" class="form__label">Nové heslo znovu:</label>
            <span style="minHeight: 9em;" id="msg2"></span>
        </div>

        <div id="submit" class="button accept" onclick="document.forms['restore'].submit();" >Uložit nové heslo</div>

    </form>

    <?php endif; ?>
</div>