<div class="index-section gdpr">
    <div class="index-section-title">Podmínky užití:</div>

    <p>
        <strong>Základní pojmy:</strong><br />
        <br />
        <strong>Provozovatel</strong> = Tomáš Podolský (podolsky.tomas@gmail.com)<br />
        <strong>Portál</strong> = <a href="http://gewrit.4fan.cz">gewrit.4fan.cz</a><br />
        <strong>Uživatel</strong> = osoba, která si vytvořila profil na Portálu<br />
        <strong>Profil</strong> = formulářem vytvořené uživatelské rozhraní Uživatele, včetně jeho osobních i dalších údajů<br />
        <strong>GDPR</strong> = nařízení EU 2016/679 ze dne 27. dubna 2016 o ochraně fyzických osob v souvislosti se zpracováním Osobních údajů a o 
            volném pohybu těchto údajů a o zrušení Směrnice 95/46/ES (obecné nařízení o ochraně Osobních údajů).<br />
        <strong>Občanský zákoník</strong> = zákon č. 89/2012 Sb. (občanský zákoník)<br />
        <strong>PU</strong> = tyto podmínky užití<br />
    </p>

    <h2>Vytvořený Profil Uživatele</h2>

    <p>Osoba, která chce využívat veškeré funkce a výhody Portálu, si zdarma vytvoří vyplněním formuláře na Portálu Profil. Při jeho vytváření je povinna zadat pravdivé údaje, 
        výhradně o sobě.</p>
    <p>Do Profilu se Uživatel přihlašuje pod uživatelským jménem (přezdívkou) a heslem. Pokud heslo zapomene, může si jej obnovit prostřednictvím k tomu určeného formuláře na Portále.
        V případě, že Uživatel umožní využívání svého Profilu třetím osobám a dojde mu tím k nějaké škodě, Provozovatel za tuto škodu neodpovídá.</p>
    <p>Provozovatel si vyhrazuje právo Profil Uživatele kdykoliv zrušit, a to bez udání důvodu a upozornění. Především mohou být smazány Profily Uživatelů, kteří se po dobu 
        delší než 4 roky nepřihlásili do Portálu. Uživatel může kdykoliv sám zrušit svůj Profil ve svém uživatelském rozhraní. Zrušením Profilu se plně smažou všechna data, 
        která Provozovatel o Uživateli zpracovává a zároveň dojde k odvolání souhlasu se zpracováním osobních údajů Uživatele.</p>
    <p>Uživatel bere na vědomí, že jeho Profil nemusí být nepřetržitě dostupný. Provozovatel si totiž vyhrazuje právo bez předchozího upozornění změnit či zrušit jakoukoliv 
        poskytovanou službu na Portálu nebo provádět údržbu systému, při které mohou být některé služby nedostupné. Provozovatel tak nezodpovídá za jakoukoliv vzniklou škodu.</p>

    <h2>Obsah Portálu</h2>

    <p>Provozovatel neodpovídá za Uživatelem zveřejněný obsah na portále, za něj odpovídá Uživatel sám, včetně skutečnosti, že takový obsah neporušuje práva třetích osob.</p>
    <p>Uživatel souhlasí s tím, že Provozovatel je oprávněn vymazat, pozměnit či zablokovat jakýkoliv údaj, příspěvek, informaci, odkaz či jiný obsah. 
        Důvodem tohoto je zejména závadnost předmětného obsahu, a to mimo jiné i proto, že je nepřesný, zavádějící, nesmyslný či jinak neodpovídá skutečnosti, 
        nebo je v rozporu s dobrými mravy nebo závadný jiným způsobem. Zhodnocení povahy obsahu včetně jeho případné závadnosti náleží výlučně Provozovateli. 
        Tento výmaz provádí Provozovatel bez nutnosti obstarat souhlas Uživatele, upozornění či udání důvodu.</p>
    <p>Obsah, který bude Uživatelem na Portál nahrán (s výjimkou osobních údajů a osobních zpráv) není považován za důvěrný ani soukromý, a může být Provozovatelem kopírován, 
        distribuován a zveřejňován třetím stranám.</p>
    <p>Uživatel prohlašuje, že poskytne ke zveřejnění na Portálu obsah, který je jeho duševním vlastnictvím, uděluje k jeho užití Uživatel Provozovateli nevýhradní, 
        přenosnou, převoditelnou, neomezenou, neúplatnou a volnou licenci. Tato licence dále přechází automaticky na právní nástupce Provozovatele, 
        případně na jakýkoliv subjekt, který se případně stane novým vlastníkem či provozovatelem Portálu.</p>
    <p>Materiály související s filmovou či knižní tematikou (např. filmové plakáty, popisy filmů, popisy anime, popisy mangy), které jsou uveřejněny na Portálu Uživateli či Provozovatelem 
        jsou uveřejněny nikoliv za komerčním účelem. Portál takovým uveřejněním nezakládá ani nestvrzuje své autorství či jiná práva k těmto materiálům.</p>


    <h2>Pravidla užívání Portálu</h2>

    <p>Veškeré služby Portálu jsou uživatelům poskytovány zdarma.</p>
    <p>Portál lze užívat pouze v rámci těchto PÚ a obecně závaznými právními předpisy.</p>
    <p>Uživatel není oprávněn využívat služeb Portálu k jakýmkoli účelům, odporujícím právním předpisům nebo níže uvedeným pravidlům: Jedná se zejména o příspěvky 
        obsahující rasistické výroky, hrubé urážky a hrubé vulgární výrazy (s výjimkou názvů seriálů, anime či mangy).</p>

    <p>Uživatel nesmí užívat portál ke komerčním účelům a nesmí na portál vkládat jakoukoliv placenou či neplacenou reklamu. Nesmí rozesílat spam.</p>

    <h2>Ochrana osobních údajů</h2>

    <p>Provozovatel je správcem osobních údajů ve smyslu relevantních ustanovení GDPR. Tímto jsou ve smyslu čl. 12 GDPR poskytnuty subjektům 
        osobních údajů informace o zpracovávání a ochraně osobních údajů a s tím souvisejících právech. 
        Provozovatel zpracovává osobní údaje v souladu s GDPR, případně dalšími relevantními právními předpisy a při současném šetření práv osob, jejichž údaje jsou zpracovány. 
        Naplňování povinností Provozovatel v oblasti ochrany osobních údajů je nedílnou součástí fungování Portálu.</p>
    <p>Kategorie zpracovávaných osobních údajů se řídí rozsahem, ve kterém byly Provozovateli poskytnuty, a to zejména prostřednictvím formuláře pro vytvoření Profilu na Portále a 
        dále údaji a informacemi získanými v rámci používání Portálu. Jedná se o poskytnutý email, přezdívku a elektronické údaje jako IP adresu či cookies, 
        dále informace týkající se oblíbených seriálů, anime, mangy či chování na Portále.</p>
    <p>Účelem zpracování osobních údajů je jejich zahrnutí do databáze provozované v rámci Portálu a případně další obchodní či jiné aktivity, pro které budou osobní údaje zpracovávány. 
        V případě Provozovatel se jedná o uzavření a plnění smluv, vymáhání práv ze smluv, plnění zákonných povinností (poskytování informací zejména orgánům činným v trestním řízení, 
        v přestupkovém či správním řízení, plnění povinností vůči mimo jiné ÚOOÚ, ČOI či ČTÚ), oprávněné zájmy Provozovatele (ochrana základních či jiných práv Provozovatel 
        vyplývajících z obecných právních předpisů, vč. ochrany majetku) a účely zahrnuté v rámci uděleného souhlasu subjektů osobních údajů.</p>
    <p>Právními tituly zpracování osobních údajů jsou zpracování za účelem uzavírání či plnění smluv, plnění právních povinností, oprávněné zájmy Provozovatele a 
        souhlas udělený subjektem osobních údajů.</p>
    <p>Osobní údaje Uživatele jsou zpracovávány manuálně i automaticky, včetně profilování. Provozovatel považuje osobní údaje za důvěrné a nebude je bez souhlasu subjektů osobních 
        údajů či zákonné povinnosti předávat třetím osobám. K osobním údajům budou mít kromě Provozovatele přístup též třetí osoby v rámci Evropské unie – zpracovatelé, 
        kteří poskytují vhodné záruky a jejichž zpracování splňuje požadavky dle platných právních předpisů, a které zajišťuje náležitou ochranu vašich práv. 
        Osobní údaje zpracovávané jsou zpracovávány po dobu trvání členství na Portálu a dobu nezbytně nutnou po jeho ukončení. Osobní údaje zpracovávané na základě souhlasu 
        jsou zpracovávány nejdéle do doby odvolání souhlasu, což lze učinit kdykoliv a ukončit tak zároveň členství na Portálu.</p>
    <p>Odvoláním souhlasu není dotčena zákonnost zpracování vycházejícího ze souhlasu, který byl dán před jeho odvoláním. Odvolání souhlasu též nemá vliv na zpracování osobních údajů, 
        které Provozovatel zpracovává na základě jiného právního základu, než je souhlas (tj. zejména je‐li zpracování nezbytné pro splnění smlouvy, právní povinnosti či z jiných důvodů 
        uvedených v platných právních předpisech).</p>
    <p>Subjekty osobních údajů mají dle Nařízení zejména následující práva:<br />
        1) Právo na informace<br />
        2) Právo na přístup k osobním údajům a jejich přenositelnost<br />
        3) Právo na opravu nepřesných osobních údajů či jejich doplnění<br />
        4) Právo na výmaz (právo být zapomenut)<br />
        5) Právo na omezení zpracování<br />
        6) Právo vznést námitku<br />
        7) Odvolat souhlas se zpracováním osobních údajů<br />
        8) Právo získat od Provozovatele potvrzení o tom, zda jsou osobní údaje subjektu zpracovávány.<br />
        <br />
        Svá práva mohou subjekty osobních údajů realizovat prostřednictvím tohoto poučení, po přihlášení v členské sekci Portálu či kontaktováním Provozovatele. 
        Pro podrobnější poučení, informace o zpracování osobních údajů a výkon svých práv se subjekt osobních údajů může obrátit na Provozovatele prostřednictvím kontaktního formuláře 
        (v patičce webu - odkaz Kontakt.)
    </p>


    <h2>Závěr</h2>

    <p>Provozovatel může tyto Podmínky užití kdykoliv doplnit či měnit (o každé změně však bude Uživatel informován prostřednictvím informace o novém znění Podmínek na Portálu.) 
        Uživatel souhlasem s nimi souhlasí i s tím, aby byly aplikovány na veškerý dosud jím poskytnutý obsah Provozovateli, v souvislosti s provozem Portálu.<br />
        Právní poměry mezi Uživateli a Provozovatelem se řídí právem České republiky (zejména Občanským zákoníkem + GDPR.)</p>
    
</div>
