<div class="index-section add-item">
    <div class="index-section-title">Přidat do DB:</div>

    <?php 
        if (!$data){ ?>
            <p>Pokud jste u nás nenašli Váš oblíbený seriál/anime/mangu, můžete nám pomoci rozšířit databázi a přidat ji. 
                Ze začátku ji uvidíte jen Vy, ale až náš tým zkontroluje, jestli je vše v pořádku, zviditelní ji i všem ostatním uživatelům.</p>
            <p>Pokud chcete přidat seriál, najděte si jej na <a href="https://www.csfd.cz/" target="_blank">CSFD.cz</a> 
                a zkokpírujte odkaz na něj do pole níže. Pokud chcete přidat anime/mangu, vyhledejte na 
                <a href="https://www.anime-planet.com/" target="_blank">Anime-Planet.com</a>. Nezapomeňte vyplnit taky antispam :-).</p>

            <form id="analyze" method="post">

                <div class="form__group field" title="Odkaz na sledování/čtení.">
                    <input type="link" class="form__field" placeholder="Odkaz :" name="url" id='url'/>
                    <label for="name" class="form__label">Odkaz :</label>
                </div>

                <div class="form__group field" title="Odkaz na sledování/čtení.">
                    <input type="text" class="form__field" placeholder="Letošní rok :" name="antispam" id='antispam'/>
                    <label for="name" class="form__label">Letošní rok :</label>
                </div>

                <div class="button accept" title="Zkontroluje odkaz a pokusí se získat informace pro přidání do databáze." 
                    onclick="document.forms['analyze'].submit();">Analyzovat</div>
            </form>


        <?php } else {

            if (strlen($data['genre']) > 25) { $genre = substr($data['genre'],0,20) . "...";} else { $genre = $data['genre']; }; ?>
            <p>Chcete přidat tuto položku?</p>
            <div class="unitBox">
                <img src="<?= $data['image'] ?>">
                <div class="unitBoxText">
                    <strong> <?= $data['name'] ?> </strong> <i class="fa fa-info-circle" title="<?= $data['description'] ?>"></i><br>
                    <div>
                        <?= $data['year'] ?><br>
                        <span title="<?= $data['genre'] ?>">Žánr: <?=  $genre ?></span>
                    </div> 
                    <?php if ($data['type'] == 'serial'): ?>
                        <a href="<?= $data['linkCsfd'] ?>" title="odkaz na CSFD" target="_blank"><li class="csfd">CSFD</li> </a> 
                        <a href="<?= $data['linkImdb'] ?>" title="odkaz na IMDB" target="_blank"><li class="imdb">IMDB</li> </a>
                    <?php endif;
                    if (($data['type'] == 'anime') || ($data['type'] == 'manga')): ?>
                        <a href="<?= $data['linkAp'] ?>" title="odkaz na ANIME-PLANET" target="_blank"><li class="ap">Anime-planet</li> </a>
                        <?php endif; ?>
                </div>
            </div>
            <form method="post">
                <input type="hidden" name="name" value="<?= $data['name'] ?>"/>
                <input type="hidden" name="image" value="<?= $data['image'] ?>"/>
                <input type="hidden" name="year" value="<?= $data['year'] ?>"/>
                <input type="hidden" name="genre" value="<?= $data['genre'] ?>"/>
                <input type="hidden" name="linkCsfd" value="<?= $data['linkCsfd'] ?>"/>
                <input type="hidden" name="linkImdb" value="<?= $data['linkImdb'] ?>"/>
                <input type="hidden" name="linkAp" value="<?= $data['linkAp'] ?>"/>
                <input type="hidden" name="description" value="<?= $data['description'] ?>"/>
                <input type="hidden" name="onlyFor" value="<?= $user ?>"/>
                <input type="hidden" name="type" value="<?= $data['type'] ?>"/>
                <input type="submit" value="Ano" />
            </form>                                                                                 

        <?php }
    ?>

</div>
