<div class="index-section detail-section">
    <?php 
    switch ($type){
        case 'serial':
            $infoText = "Chcete přidat tento seriál na svůj seznam?";
            break;
        case 'anime':
            $infoText = "Chcete přida toto anime na svůj seznam?";
            break;
        case 'manga':
            $infoText = "Chcete přidat tuto mangu na svůj seznam?";
            break;
    } ?>
    <div class="index-section-title">
        Přidat na seznam
    </div>

    <img src="<?= $data['image'] ?>">

    <div class="detail-text">
    
        <div> 
            <u><?= $infoText ?> </u>
        </div>

        <div class="detail-name"> 
            <?= $data['name'] ?> 
        </div>

        <h4>Vaše aktuální pozice ve sledování/čtení:</h4>
        <?php include "views/progressForm.phtml"?>
        
    </div>

</div>