<div class="index-section detail-section">
    <?php 
    switch ($type){
        case 'serial':
            $infoText = "Chcete přidat tento seriál na svůj seznam?";
            break;
        case 'anime':
            $infoText = "Chcete přida toto anime na svůj seznam?";
            break;
        case 'manga':
            $infoText = "Chcete přidat tuto mangu na svůj seznam?";
            break;
    } ?>
    <div class="index-section-title">
        Přidat na seznam
    </div>

    <img src="<?= $data['image'] ?>">

    <div class="detail-text">
    
        <div> 
            <u><?= $infoText ?> </u>
        </div>

        <div class="detail-name"> 
            <?= $data['name'] ?> 
        </div>

        <h4>Vaše aktuální pozice ve sledování/čtení:</h4><br>
        <form id="change<?= $line['_id']?>" method="post">
            <label for="series">Série: </label>
                <input type="number" id ="series" name="series" class="progress-input" value="<?= $records[$i]['series'] ?>" title="Série. Pokud nemá série, nechejte prázdné políčko, případně nulu.">
            <label for="series"><?php if (($type == 'serial') || ($type == 'anime')) echo "Díl:"; else echo "Kapitola:" ?></label>
                <input type="number" id ="episode" name="episode" class="progress-input" value="<?= $records[$i]['episode'] ?>"><br><br>
            <label for="link">Odkaz na sledování/čtení: </label>
                <input type="link" id ="link" name="link" class="linkInput" value="<?= $records[$i]['link'] ?>" title="Odkaz na sledování/čtení."><br><br>
            <label for="releaseDay" title="V tento den vás upozorníme na hlavní stránce, že vychází nový díl.">Který den v týdnu pravidelně vychází: </label><br>
                
            <div class="form-days-container">
                <div>
                    <input type="checkbox" name="releaseDay[]" value="1" id="po" class="day-checkbox"/>
                    <label for="po"><div  class="day-checkbox-label">Po</div></label>
                </div>

                <div>
                    <input type="checkbox" name="releaseDay[]" value="2" id="ut" class="day-checkbox"/>
                    <label for="ut"><div  class="day-checkbox-label">Út</div></label>
                </div>

                <div>
                    <input type="checkbox" name="releaseDay[]" value="3" id="str" class="day-checkbox"/>
                    <label for="str"><div  class="day-checkbox-label">Stř</div></label>
                </div>

                <div>
                    <input type="checkbox" name="releaseDay[]" value="4" id="ct" class="day-checkbox"/>
                    <label for="ct"><div  class="day-checkbox-label">Čt</div></label>
                </div>

                <div>
                    <input type="checkbox" name="releaseDay[]" value="5" id="pa" class="day-checkbox"/>
                    <label for="pa"><div  class="day-checkbox-label">Pá</div></label>
                </div>

                <div>
                    <input type="checkbox" name="releaseDay[]" value="6" id="so" class="day-checkbox"/>
                    <label for="so"><div  class="day-checkbox-label">So</div></label>
                </div>

                <div>
                    <input type="checkbox" name="releaseDay[]" value="7" id="ne" class="day-checkbox"/>
                    <label for="ne"><div  class="day-checkbox-label">Ne</div></label>
                </div>
            </div>


            <label for="status">Na který seznam přidat?</label>
                <select id="status" name="status">
                    <option value="1">Sleduji</option>
                    <option value="2">Pozastaveno</option>
                    <option value="3">Odloženo</option>
                    <option value="4">Dokončeno</option>
                    <option value="5">Vyhnout se tomu</option>
                    <option value="6">Chci shlédnout/přečíst</option>
                </select><br><br>
            <div class="button accept" onclick="document.forms['change<?= $line['_id']?>'].submit();">Přidat na seznam</div>
        </form>
        
    </div>

</div>