<div class="index-section add-item">
    <div class="index-section-title">Přidat do DB</div>

    <?php 
        if (!$data){ ?>
            <p>Pokud jste u nás nenašli Váš oblíbený seriál/anime/mangu, můžete nám pomoci rozšířit databázi a přidat ji. 
                Ze začátku ji uvidíte jen Vy, ale až náš tým zkontroluje, jestli je vše v pořádku, zviditelní ji i všem ostatním uživatelům.</p>
            <p>Pokud chcete přidat seriál, najděte si jej na <a href="https://www.csfd.cz/" target="_blank">CSFD.cz</a> 
                a zkokpírujte odkaz na něj do pole níže. Pokud chcete přidat anime/mangu, vyhledejte na 
                <a href="https://www.anime-planet.com/" target="_blank">Anime-Planet.com</a>. Nezapomeňte vyplnit taky antispam :-).</p>

            <form id="analyze" method="post">

                <div class="form__group field" title="Odkaz na sledování/čtení.">
                    <input type="url" class="form__field" placeholder="Odkaz :" name="url" id='url'/>
                    <label for="name" class="form__label">Odkaz :</label>
                </div>

                <div class="form__group field" title="Odkaz na sledování/čtení.">
                    <input type="text" class="form__field" placeholder="Letošní rok :" name="antispam" id='antispam'/>
                    <label for="name" class="form__label">Letošní rok :</label>
                </div>

                <div class="button accept" title="Zkontroluje odkaz a pokusí se získat informace pro přidání do databáze." 
                    onclick="document.forms['analyze'].submit();">Analyzovat</div>
            </form>


        <?php } else { 
            
            switch ($data['type']){
                case "anime":
                    $itemType = "Anime";
                    break;
                case "manga":
                    $itemType = "Manga";
                    break;
                case "serial":
                    $itemType = "Seriál";
            }?>

            <div class="add-item-details">
                <div>
                    <div>
                        <img src="<?= $data['image'] ?>">
                    </div>

                    <div class="detail-text">
                        <div class="detail-name"> 
                            <?= $data['name'] ?> 
                        </div>

                        <div class="detail-row"> 
                            <div><?= $data['year'] ?></div>
                        </div>

                        <div>
                            <?= $itemType ?>
                        </div>

                        <div>
                            <u>Žánr:</u> <?= $data['genre'] ?>
                        </div>

                        <div>
                            <u>Popis:</u> <?= $data['description'] ?>
                        </div>

                        <div class="detail-links">
                            <?php if ($itemType == 'Seriál') : ?>
                                <a href="<?= $data['linkCsfd'] ?>" title="odkaz na CSFD" target="_blank"><div class="button csfd">CSFD</div> </a> 
                                <a href="<?= $data['linkImdb'] ?>" title="odkaz na IMDB" target="_blank"><div class="button imdb">IMDB</div> </a>
                            <?php else : ?>
                                <a href="<?= $data['linkAp'] ?>" title="odkaz na Anime-planet" target="_blank"><div class="button ap">Anime-planet</div> </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                
                <form id="add" method="post">
                    <input type="hidden" name="name" value="<?= $data['name'] ?>"/>
                    <input type="hidden" name="image" value="<?= $data['image'] ?>"/>
                    <input type="hidden" name="year" value="<?= $data['year'] ?>"/>
                    <input type="hidden" name="genre" value="<?= $data['genre'] ?>"/>
                    <input type="hidden" name="linkCsfd" value="<?= $data['linkCsfd'] ?>"/>
                    <input type="hidden" name="linkImdb" value="<?= $data['linkImdb'] ?>"/>
                    <input type="hidden" name="linkAp" value="<?= $data['linkAp'] ?>"/>
                    <input type="hidden" name="description" value="<?= $data['description'] ?>"/>
                    <input type="hidden" name="onlyFor" value="<?= $user ?>"/>
                    <input type="hidden" name="type" value="<?= $data['type'] ?>"/>
                    <p>Je toto položka, kterou chcete přidat do do databáze?</p>
                    <div class="button accept" onclick="document.forms['add'].submit();">Ano, přidat do databáze</div>
                </form>  
            </div>

        <?php }
    ?>

</div>
