<div class="index-section">

    <div class="index-section-title">Přihlášení:</div>

    <div class="report-container">

        <form id="login" method="post">

            <div class="form__group field" title="Vaše uživatelské jméno.">
                <input type="text" class="form__field" placeholder="Uživatelské jméno" name="username" id='username'/>
                <label for="username" class="form__label">Uživatelské jméno:</label>
            </div>

            <div class="form__group field" title="Vaše heslo.">
                <input type="password" class="form__field" placeholder="Heslo" name="password" id='password'/>
                <label for="password" class="form__label">Heslo:</label>
            </div>

            <div class="button accept" onclick="document.forms['login'].submit();" >Přihlásit se</div>
        </form>

        <p>Pokud ještě nemáte účet, <a href="registrace">zaregistrujte se</a>.</p>
        <p>Pokud jste zapomněli heslo, <a href="obnovit">zde</a> si jej můžete obnovit.</p>
    </div>
</div>