<div class="kontaktContainer">
<h1>Přihlášení</h1>

<form method="post">
    Jméno<br />
    <input type="text" name="username" /><br />
    Heslo<br />
    <input type="password" name="password" /><br />
    <input type="submit" value="Přihlásit" />
</form>

<p>Pokud ještě nemáte účet, <a href="registrace">zaregistrujte se</a>.</p>
<p>Pokud jste zapomněli heslo, <a href="obnovit">zde</a> si jej můžete obnovit.</p>
</div>