<?php if (!$type):?>
<a href="/muj-seznam/sleduji">Sleduji</a>
<a href="/muj-seznam/planovane">Chci si přečíst/shlédnout</a>
<a href="/muj-seznam/pozastaveno">Pozastaveno</a>
<a href="/muj-seznam/odlozeno">Odloženo</a>
<a href="/muj-seznam/dokonceno">Dokončeno</a>
<a href="/muj-seznam/nesledovat">Nesledovat</a> || 
<a href="/muj-seznam/">Vše</a> <br><br>
<?php endif; ?>

<div class="index-section">

    <?php if ($seznamType == 'all'){ 
        switch ($type){
            case 'serial':
                $titleText = "Seznam seriálů";
                break;
            case 'anime':
                $titleText = "Seznam anime";
                break;
            case 'manga':
                $titleText = "Seznam mangy";
                break;
        } ?>

        <div class="index-section-title"><?= $titleText ?></div>

        <form class="search-section" method="GET" id="search" action="/<?php echo ($type == 'serial')? "serialy" : $type ?>">
            <label for="search"><i class="fas fa-search"></i></label>
            <input title="Zadejte hledaný text. Vyhledává slova o minimální délce 3 písmena." id="search" type="text" name="hledat" value="<?php echo $_GET['hledat']; ?>">
            <div class="button accept" onclick="document.forms['search'].submit();" title="Vyhledá v databázi vámi zvolená slova">Hledej</div>
        </form>

        <?php include "views/items.phtml";
        include_once "views/pages.phtml";

    } elseif ($seznamType == 'my'){ ?>
        <div class="index-section-title">Můj seznam</div>
        <form class="search-section" method="post">
            <div style="display: flex;">
                <input type="hidden" name="form" value="true">
                <input type="checkbox" onChange="this.form.submit()" name="checking[]" value="anime" <?php if (strpos($checked, 'anime') !== false) { echo "checked"; }?>/> Anime | 
                <input type="checkbox" onChange="this.form.submit()" name="checking[]" value="manga" <?php if (strpos($checked, 'manga') !== false) { echo "checked"; }?>/> Manga |
                <input type="checkbox" onChange="this.form.submit()" name="checking[]" value="serial" <?php if (strpos($checked, 'serial') !== false) { echo "checked"; }?>/> Seriály ||
                <input type="checkbox" onChange="this.form.submit()" name="checking[]" value="releaseDay" <?php if (strpos($checked, 'releaseDay') !== false) { echo "checked"; }?>/> Jen dnešní
            </div>
        </form><br />
        
        <?php include "views/my-items.phtml"; 
        include_once "views/pages.phtml";
    }?>
</div>