<div class="index-section">

    <?php if ($seznamType == 'all'){ 
        switch ($type){
            case 'serial':
                $titleText = "Seznam seriálů";
                break;
            case 'anime':
                $titleText = "Seznam anime";
                break;
            case 'manga':
                $titleText = "Seznam mangy";
                break;
        } ?>

        <div class="index-section-title"><?= $titleText ?></div>

        <form class="search-section" method="GET" id="search" action="/<?php echo ($type == 'serial')? "serialy" : $type ?>">
            <label for="search"><i class="fas fa-search"></i></label>
            <input title="Zadejte hledaný text. Vyhledává slova o minimální délce 3 písmena." id="search" type="text" name="hledat" value="<?php echo $_GET['hledat']; ?>">
            <div class="button accept" onclick="document.forms['search'].submit();" title="Vyhledá v databázi vámi zvolená slova">Hledej</div>
        </form>

        <?php include "views/items.phtml";
        include_once "views/pages.phtml";

    } elseif ($seznamType == 'my'){ ?>
        <div class="index-section-title">Můj seznam</div>

        <?php if (!$type):?>
            <div class="my-list-submenu">
                <ul>
                    Moje seznamy :
                    <a href="/muj-seznam/sleduji"><li <?php if ($active == 'sleduji') { echo "class='my-list-submenu-active' "; }?>>Sleduji</li></a>
                    <a href="/muj-seznam/planovane"><li <?php if ($active == 'planovane') { echo "class='my-list-submenu-active' "; }?>>Chci si přečíst/shlédnout</li></a>
                    <a href="/muj-seznam/pozastaveno"><li <?php if ($active == 'pozastaveno') { echo "class='my-list-submenu-active' "; }?>>Pozastaveno</li></a>
                    <a href="/muj-seznam/odlozeno"><li <?php if ($active == 'odlozeno') { echo "class='my-list-submenu-active' "; }?>>Odloženo</li></a>
                    <a href="/muj-seznam/dokonceno"><li <?php if ($active == 'dokonceno') { echo "class='my-list-submenu-active' "; }?>>Dokončeno</li></a>
                    <a href="/muj-seznam/nesledovat"><li <?php if ($active == 'nesledovat') { echo "class='my-list-submenu-active' "; }?>>Nesledovat</li></a>
                    <a href="/muj-seznam/"><li <?php if ($active == 'all') { echo "class='my-list-submenu-active' "; }?>>Vše</li></a>
                </ul>
            </div>
        <?php endif; ?>

        <form class="search-section" method="post">
            <div style="display: flex;">
                <input type="hidden" name="form" value="true">
                <input type="checkbox" onChange="this.form.submit()" name="checking[]" value="anime" <?php if (strpos($checked, 'anime') !== false) { echo "checked"; }?>/> Anime | 
                <input type="checkbox" onChange="this.form.submit()" name="checking[]" value="manga" <?php if (strpos($checked, 'manga') !== false) { echo "checked"; }?>/> Manga |
                <input type="checkbox" onChange="this.form.submit()" name="checking[]" value="serial" <?php if (strpos($checked, 'serial') !== false) { echo "checked"; }?>/> Seriály ||
                <input type="checkbox" onChange="this.form.submit()" name="checking[]" value="releaseDay" <?php if (strpos($checked, 'releaseDay') !== false) { echo "checked"; }?>/> Jen dnešní
            </div>
        </form><br />
        
        <?php include "views/my-items.phtml"; 
        include_once "views/pages.phtml";
    }?>
</div>