<div class="index-section">

    <?php if ($seznamType == 'all'){ 
        switch ($type){
            case 'serial':
                $titleText = "Seznam seriálů";
                break;
            case 'anime':
                $titleText = "Seznam anime";
                break;
            case 'manga':
                $titleText = "Seznam mangy";
                break;
        } ?>

        <div class="index-section-title"><?= $titleText ?></div>

        <form class="search-section" method="GET" id="search" action="/<?php echo ($type == 'serial')? "serialy" : $type ?>">
            <label for="search"><i class="fas fa-search"></i></label>
            <input title="Zadejte hledaný text. Vyhledává slova o minimální délce 3 písmena." id="search" type="text" name="hledat" value="<?php echo $_GET['hledat']; ?>">
            <div class="button accept" onclick="document.forms['search'].submit();" title="Vyhledá v databázi vámi zvolená slova">Hledej</div>
        </form>

        <?php include "views/items.phtml";
        include_once "views/pages.phtml";

    }?>
</div>