<div class="index-section">
    <div class="index-section-title">Statistiky portálu:</div>

    <div>
        <p>
            <strong>Začneme statistikou uživatelů:</strong><br />
            Počet uživatelů - <?= $totalUsers ?> <br />
            Počet moderátorů - <?= $totalMods ?> <br />
            Počet zabanovaných uživatelů - <?= $totalBannedUsers ?> <br />
            Počet všech záznamů všech uživatelů - <?= $totalRecords ?>
        </p>
        <p>
            <strong>A co se týče rozsáhlosti databáze:</strong><br />
            Počet seriálů - <?= $totalSerial ?> <br />
            Počet anime - <?= $totalAnime ?> <br />
            Počet mangy - <?= $totalManga ?>
        </p>
        
    </div>
    
</div>
