<h1>Vítejte na GEWRITu</h1>

    <?php if(count($today) != 0):?>
    <div class="index-section today">
        <div class="index-section-title">Dnes vychází:</div>
        <?php $data = $today;
        $type = 'today'; $latestData = $data; include "views/indexItems.phtml";
        endif;
    ?>
    </div>

    <div class="index-section">
        <div class="index-section-title">Nejnovější seriály:</div>
        <?php $type = 'serial'; $latestData = $latestSerials; include "views/indexItems.phtml"; ?>
    </div>

    <div class="index-section">
        <div class="index-section-title">Nejnovější anime:</div>
        <?php $type = 'anime'; $latestData = $latestAnime; include "views/indexItems.phtml"; ?>
    </div>

    <div class="index-section">
        <div class="index-section-title">Nejnovější manga:</div>
        <?php $type = 'manga'; $latestData = $latestManga; include "views/indexItems.phtml"; ?>
    </div>

